### ISSUE TITLE
Documentation for the code

### ISSUE THREAD

**Issue by SUDHA489** [GAVINESHWAR/Assignment_Plagarism_Checker#1]
Description lo I would like to make good documentation for the code and make it look attractive and meaningful

@GAVINESHWAR 
 assign me this issue.

Thank You

**Comment by GAVINESHWAR** [comment]
I am assigning this  you to you make good README file for the Project.

@SUDHA489

**Comment by GAVINESHWAR** [comment]
@SUDHA489  issue as been closed as complete.

Thank you
